server:
  servlet:
    context-path: /api
  # add message in error response 
  error:
    include-message: always

logging:
  config: classpath:logback-spring.xml

spring:
  redis:
    host: localhost
    port: 6379
    password: PASSWORD1@#
    